### ISSUE TITLE
keycloak configuration

### ISSUE THREAD

**Issue by mataoqun** [Activiti/activiti-modeling-app#72]
Hello, I have encountered the following problem：

I have modified the file [app.config.json](https://github.com/Activiti/activiti-modeling-app/blob/master/src/app.config.json) and changed it to my local keycloak authentication service, but I will still jump to http://activiti-cloud-gateway.35.204.66.71.nip.io

The following is my configuration
![image](https://user-images.githubusercontent.com/11460761/53626682-61088580-3c41-11e9-9c9b-52cb55f230e1.png)

Am I wrong?

**Comment by fcorti** [comment]
Hi @mataoqun,

Sorry for the late reply.

The authentication is managed also on server side by Activiti.
Changing the configuration on the front-end app only, is not enough.

I hope this will help you.

Closing this issue, because pretty old.
Feel free to reopen it (or open a new one) if needed.

Cheers.
